DROP INDEX `jobs_fullpath1_idx`;
DROP INDEX `jobs_fullpath2_idx`;
DROP INDEX `jobs_fullpath3_idx`;
DROP INDEX `jobs_fullpath4_idx`;
DROP INDEX `jobs_fullpath5_idx`;
DROP INDEX `jobs_fullpath6_idx`;
DROP INDEX `jobs_fullpath7_idx`;
DROP INDEX `jobs_fullpath8_idx`;
DROP INDEX `jobs_fullpath9_idx`;
DROP INDEX `jobs_fullpath10_idx`;
DROP INDEX `jobs_fullpath11_idx`;
DROP INDEX `jobs_fullpath12_idx`;
DROP INDEX `jobs_fullpath13_idx`;
DROP INDEX `jobs_fullpath14_idx`;
DROP INDEX `jobs_fullpath15_idx`;

ALTER TABLE `jobs`
  DROP COLUMN `full_path1`,
  DROP COLUMN `full_path2`,
  DROP COLUMN `full_path3`,
  DROP COLUMN `full_path4`,
  DROP COLUMN `full_path5`,
  DROP COLUMN `full_path6`,
  DROP COLUMN `full_path7`,
  DROP COLUMN `full_path8`,
  DROP COLUMN `full_path9`,
  DROP COLUMN `full_path10`,
  DROP COLUMN `full_path11`,
  DROP COLUMN `full_path12`,
  DROP COLUMN `full_path13`,
  DROP COLUMN `full_path14`,
  DROP COLUMN `full_path15`;

ALTER TABLE `jobs`
  DROP COLUMN `full_path`,