// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type workerTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *workerTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("highkick_workers").
func (v *workerTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *workerTableType) Columns() []string {
	return []string{
		"id",
		"sid",
		"process_sid",
		"stopped",
		"running_jobs_count",
		"healthchecked_at",
		"created_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *workerTableType) NewStruct() reform.Struct {
	return new(Worker)
}

// NewRecord makes a new record for that table.
func (v *workerTableType) NewRecord() reform.Record {
	return new(Worker)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *workerTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// WorkerTable represents highkick_workers view or table in SQL database.
var WorkerTable = &workerTableType{
	s: parse.StructInfo{
		Type:    "Worker",
		SQLName: "highkick_workers",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int", Column: "id"},
			{Name: "SID", Type: "string", Column: "sid"},
			{Name: "ProcessSID", Type: "string", Column: "process_sid"},
			{Name: "Stopped", Type: "bool", Column: "stopped"},
			{Name: "RunningJobsCount", Type: "int", Column: "running_jobs_count"},
			{Name: "HealthcheckedAt", Type: "time.Time", Column: "healthchecked_at"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
		},
		PKFieldIndex: 0,
	},
	z: new(Worker).Values(),
}

// String returns a string representation of this struct or record.
func (s Worker) String() string {
	res := make([]string, 7)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "SID: " + reform.Inspect(s.SID, true)
	res[2] = "ProcessSID: " + reform.Inspect(s.ProcessSID, true)
	res[3] = "Stopped: " + reform.Inspect(s.Stopped, true)
	res[4] = "RunningJobsCount: " + reform.Inspect(s.RunningJobsCount, true)
	res[5] = "HealthcheckedAt: " + reform.Inspect(s.HealthcheckedAt, true)
	res[6] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Worker) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.SID,
		s.ProcessSID,
		s.Stopped,
		s.RunningJobsCount,
		s.HealthcheckedAt,
		s.CreatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Worker) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.SID,
		&s.ProcessSID,
		&s.Stopped,
		&s.RunningJobsCount,
		&s.HealthcheckedAt,
		&s.CreatedAt,
	}
}

// View returns View object for that struct.
func (s *Worker) View() reform.View {
	return WorkerTable
}

// Table returns Table object for that record.
func (s *Worker) Table() reform.Table {
	return WorkerTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Worker) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Worker) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Worker) HasPK() bool {
	return s.ID != WorkerTable.z[WorkerTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Worker) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = WorkerTable
	_ reform.Struct = (*Worker)(nil)
	_ reform.Table  = WorkerTable
	_ reform.Record = (*Worker)(nil)
	_ fmt.Stringer  = (*Worker)(nil)
)

func init() {
	parse.AssertUpToDate(&WorkerTable.s, new(Worker))
}
